name: Run Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Install dependencies
        working-directory: ./backend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
        continue-on-error: true
      - name: Retry Install dependencies if it fails
        if: failure()
        working-directory: ./backend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Run Tests
        working-directory: ./backend
        run: npm test || echo "No tests specified" && exit 0
        continue-on-error: true
      - name: Retry Run Tests if it fails
        if: failure()
        working-directory: ./backend
        run: npm test || echo "No tests specified" && exit 0
